# Học thêm https://docs.drone.io/pipeline/kubernetes/examples/language/golang/
kind: pipeline
type: kubernetes
name: default

steps:
- name: test
  image: golang
  commands:
  - go test
  - go build